### ISSUE TITLE
Right panel alignment issue on Safari (Version 9.1 (11601.5.17.1))

### ISSUE THREAD

**Issue by loicsf** [sourcey/spectacle#1]
It works fine on Chrome (OSX) but on Safari I get the right panel mis-aligned (see attachment).
<img width="1674" alt="spectacle-safari" src="https://cloud.githubusercontent.com/assets/1976539/15413117/21db69ac-1de2-11e6-8953-ee4eb7d33eb9.png">

**Comment by auscaster** [comment]
Thanks for reporting this. If you fixed this issue a PR would be great, otherwise I'll try to find some time over the next week or so.

**Comment by otistamp** [comment]
Same issue on chromium, latest. It looks like a screen size issue once the viewport width is greater than 1390px and there is a max width on the row

    `#spectacle article .doc-row { max-width: 78.94737rem; }`

I can submit a pull request, but not sure how you would like to solve the issue. Simply taking out the max-width solves it but that's your call.

**Comment by auscaster** [comment]
Hi Otis, please feel free to submit a PR and I'll see it merged in :) Cheers

**Comment by fgabolde** [comment]
@auscaster I still have that exact issue on Chromium and Chrome with the latest commit of Spectacle.

**Comment by auscaster** [comment]
Hi @fgabolde, does the above fix solve your issue?

**Comment by fgabolde** [comment]
If you mean removing manually `max-width` from the generated CSS, yes it does.

But in the latest version from the repository I still have `max-width` set and the layout is broken.

**Comment by auscaster** [comment]
OK thanks, I'll push a fix for it tomorrow unless you beat me to it ;)

**Comment by auscaster** [comment]
Fixed on master

**Comment by fgabolde** [comment]
Yep, it displays fine now, thanks!
