### ISSUE TITLE
How to use $ref in another JSON file in different folder

### ISSUE THREAD

**Issue by cheesiangcs** [sourcey/spectacle#121]
Basically, I have a "_Parent.json_" which include a definition "_Relationship_" that **$ref** to "_def/Relationship.json_".

Then I have a "_Person.json_" file (same folder under /Def) which include a $ref to "Relationship.json" file as well. 

The reason I'm splitting definition from the main json file is because I have multiple large definition schema and I do not want to put everything into a single json. 

**Folder Structure**
![image](https://user-images.githubusercontent.com/35026330/36338268-5a518cda-13e5-11e8-9496-0ce8933a6033.png)

When I use the spectacle command to generate the HTML output, it look like this, 
**_Schema Definitions_**

- Person
- Relationship
- def/Relationship.json

![image](https://user-images.githubusercontent.com/35026330/36338483-38e7d184-13eb-11e8-95db-9e24d316c050.png)

FYI, "_Relationship_" & "_def/Relationship.json_" are both having the same type, name, properties, example etc. 

**Question**:: Why the Schema Definition contains both "_Relationship_" and "_def/Relationship.json_" ? How to set both "_Parent.json_" and "_Person.json_" $ref to the same "_Relationship.json_" ? 

For example, **_Schema Definitions_**

- Person
- Relationship

-----------------------------------------------------------------

**Parent.json**
![image](https://user-images.githubusercontent.com/35026330/36338271-6393a030-13e5-11e8-93cc-15b59f8593f8.png)

**Person.json**
![image](https://user-images.githubusercontent.com/35026330/36338281-a407ee64-13e5-11e8-848e-c077ded30222.png)

**Comment by auscaster** [comment]
The issue here is that remote references are prefixed with the file location and extension. I'm not sure how to get around that other than to change that behaviour completely, which might be a possibility if enough people require it.

If you really want to see that behaviour changed I would also accept a PR with the update.
