### ISSUE TITLE
if a path's summary contains a period, it's used for the link and title

### ISSUE THREAD

**Issue by spencer-rig** [sourcey/spectacle#124]
spectacle version 0.9.13, swagger spec version 2.0 (generated by [goswagger](https://goswagger.io/) 0.13.0)

I noticed something strange when I ran spectacle against my swagger json. In the left sidebar some of my endpoints were listed by their method and endpoint, and some were listed by their summary. I did an audit and realized the pattern: those with a period "." in their summary were the ones listed by their summary.

![sidebar](https://www.dropbox.com/s/iohnxjqghf2jqb4/sidebar.png?raw=1)

Further, the main content would display the summary as the title, and have a "Path" block under it. 

![unexpected content](https://www.dropbox.com/s/yw0gmj9r3jhp6jf/content-a.png?raw=1)

The behavior I expect is for the title to be the method and path, and there to be a Description block under it.

![expected content](https://www.dropbox.com/s/o7ofocciejc2ykz/content-b.png?raw=1)

**Comment by yyamano** [comment]
@spencer-rig I can't reproduce it. Could you upload the swagger file?

**Comment by spencer-rig** [comment]
Maybe it's more complex than just the period at the end of the summary. Here's a swagger json that shows the behavior for me (spectacle v 0.9.13)
[swagger.txt](https://github.com/sourcey/spectacle/files/1881107/swagger.txt)

**Comment by spencer-rig** [comment]
Scrubbing out the parameters and responses also ends with the same behavior: 
[swagger2.txt](https://github.com/sourcey/spectacle/files/1881118/swagger2.txt)

**Comment by yyamano** [comment]
@spencer-rig Thank you, I got it.

The difference comes from "summary" field. Could you try to change "summary" to "description"?

```
  "paths": {
    "/admin/demodata": {
      "get": {
        "summary": "Sets up demo data and responds 200 OK.",
```

```
    "/admin/organizations": {
      "get": {
        "description": "Returns a list of Organizations",
```

**Comment by spencer-rig** [comment]
Gotcha, ok. I think my issue stems from using a different tool: that if my code comment includes a period it'll be parsed by goswagger as a `summary` instead of a `description`. Thanks for the clues and insight!
