### ISSUE TITLE
Boolean examples look like strings

### ISSUE THREAD

**Issue by bburtin** [sourcey/spectacle#129]
Thanks for maintaining this project.  I just generated docs for the first time, and they look really good.

I found a minor nit with boolean fields.  When a boolean field doesn't have `"example"` set, the sample JSON looks like this:

`"isActive": "boolean"`

which implies that the value is supposed to be a string.  I think it would be more intuitive if the default was `false`.

**Comment by yyamano** [comment]
@bburtin How about other types as below? Do you think they should have default values?

```
    {
      "id": "integer (int64)",
      "name": "string"
    }
```

**Comment by auscaster** [comment]
I understand that this might be desirable, but would prefer to keep the default functionality as is unless enough people want it changed.

To change those values you can  just provide and `example` block
