### ISSUE TITLE
Empty CSS

### ISSUE THREAD

**Issue by kalafut** [sourcey/spectacle#13]
Using the tip in #10 does let things start, but I noticed that the stylesheets, whether statically generated or served via -d, are empty.

**Comment by auscaster** [comment]
Fixed in latest version. If it works for you please close this one :)

**Comment by kalafut** [comment]
Close :-)  foundation.css is not being minimized, but the *.min.css version is what the generated HTML is trying to include.

**Comment by auscaster** [comment]
OK, some residual issues left from porting `git-contrib-scss` to `grunt-sass`. Will fix tomorrow if time permits, PR is also welcome

**Comment by kalafut** [comment]
Hi,

I not terribly familiar with Node and Grunt, but it looks like the cssmin task just needed to run after foundation. The change in this PR seems to work for me. Note: you'd only notice the original issue on the first run, since subsequent builds would minimize foundation.css from the last time.

Thanks,
Jim

**Comment by auscaster** [comment]
Thanks Jim, that did the trick!!
