### ISSUE TITLE
Using Spectacle in AWS Lambda

### ISSUE THREAD

**Issue by andrewcretin** [sourcey/spectacle#130]
I've been trying to get Spectacle running on AWS Lambda and having no luck. 

Is there a binary for spectacle?
What would be the easiest way to run the cli command in a lambda container? (Ubuntu running 6.10)

I've played around with `pkg` to try and create an executable and then running it using `child_process` in the lambda function.

I also tried including the `app/` folder and the `spectacle-docs` npm package. Then using a node package to run command line scripts in the lambda function. Again, no success.

I've been racking my head over this, and i'm not having any success..

Ideas??

**Comment by auscaster** [comment]
I haven't played with Lambda much, and I'm not quite sure what errors you're having, but some ideas come to mind:

* Running spectacle from Docker image: https://hub.docker.com/r/sourcey/spectacle/tags/
* Installing from npm using the `-g` flag which exposes the system wide `spectacle` cli command

**Comment by auscaster** [comment]
Thanks for reporting back with your solution, glad you got it sorted out and I hope it's working well for you
