### ISSUE TITLE
Rendering issue with schemas with circular dependancies

### ISSUE THREAD

**Issue by andreaspsson** [sourcey/spectacle#141]
When a schema have circular dependancies, the rendered output looks really strange, see here:
![screen shot 2018-04-27 at 14 03 30](https://user-images.githubusercontent.com/2647060/39361698-e79145b2-4a23-11e8-83a6-2b1137acbae5.png)

Here is a small schema that illustrates the problem:
https://gist.github.com/andreaspsson/3aea82c0489de63755c0145d017c80c3

I don't know that the best way t render such structure is, but now the entire document looks kind of bloated due tho these large objects. For example on https://editor.swagger.io/ it is rendered as an empty object, maybe not super, but way better, see:

![screen shot 2018-04-27 at 14 01 06](https://user-images.githubusercontent.com/2647060/39361705-efb7856c-4a23-11e8-804f-9afd2c6726b3.png)

**Comment by tommyschnabel** [comment]
+1

**Comment by auscaster** [comment]
Just merged a fix for this! Hope it helps
