### ISSUE TITLE
x-external property when referencing external example

### ISSUE THREAD

**Issue by llirikkk** [sourcey/spectacle#146]
Hi guys.

When I reference an external example I get x-external property added to that example.

**api.yaml:**
example:
      $ref: './examples/exampleResponse.json'

**In the browser:**
{
   ...
    "x-external": "examples/exampleResponse.json"
}

Is there a way to remove this extra property?

**Comment by auscaster** [comment]
Spectacle does not currently support rendering response snippets from external files, for now please render them inline.
