### ISSUE TITLE
Spectacle deletes public/index.html

### ISSUE THREAD

**Issue by nurikabe** [sourcey/spectacle#149]
If I supply a different filename, for example:

    spectacle swagger.yaml -f api.html

Spectacle will still delete `public/index.html`

**Comment by yyamano** [comment]
spectacle deletes all *.html files.

@auscaster Are there any reasons to delete all html files rather than generated files?

https://github.com/sourcey/spectacle/blob/master/app/lib/config.js#L124-L131

```
      clean: {
          options: {
              force: true
          },
          cache: [options.cacheDir],
          assets: [options.targetDir + '/stylesheets/**/*.css', options.targetDir + '/javascripts/**/*.js'],
          html: [options.cacheDir + '/**/*.html', options.targetDir + '/**/*.html']
      },
```

**Comment by auscaster** [comment]
Any changes to the template files should be made to the view files under `app/views`
