### ISSUE TITLE
The implementation option must be passed to the Sass task

### ISSUE THREAD

**Issue by EgidioCaprino** [sourcey/spectacle#156]
```
nvm use 8.10
npm install spectacle-docs
./node_modules/.bin/spectacle swagger.yml
```
produces
```
Running "sass:foundation_scss" (sass) task
Fatal error: The implementation option must be passed to the Sass task.
```
`swagger.yml` reports no error on [editor.swagger.io](https://editor.swagger.io/).

**Comment by NordicGamer** [comment]
Hello! Exact same problem. Have you found any solution?

**Comment by pablomarambio** [comment]
Same here 😢 
[Travis log of the error](https://travis-ci.org/Multicaja/api/builds/397493970#L496) has more info.
Do you have a fix?

**Comment by smishmash** [comment]
I have the same problem. This is recent, probably due to a bug in a dependency. I have an older docker image, and an older install on my mac, that works as expected. Attempting to install the software at a new location produces this error.

**Comment by jurgob** [comment]
I have the same problem

**Comment by slide13** [comment]
**smishmash** is right. I changed grunt-sass to 2.1.0 in dependency and it worked

**Comment by offero** [comment]
It's the only dependency that has a "*" for a version number. This is why you don't do that.

**Comment by TheIDCo-ScottLeckie** [comment]
+1 
Changing the dependency to "2.1.0" in packages.json and "npm link" allowed me to work around.
Can this get updated in master? I went to do a pull request but it doesn't look like I can do so.

**Comment by auscaster** [comment]
Hi all, thanks for the PR it was just merged in.

I'll look at updating spectacle to `grunt-saas` 3.0 today to see if we can fix outstanding issue #114

**Comment by mbuguaWanjiku** [comment]
Changing grunt-sass dependency solved my issue too.

**Comment by relair** [comment]
@lorem--ipsum This solution works, in my case I needed to add 'node-sass' to my package.json and install it for it to work, but its nice to have it working with latest version.

**Comment by auscaster** [comment]
This has already been fixed on the latest package.

**Comment by medmin** [comment]
@auscaster No. I have to add the "implementation: sass," to fix this problem.

It's 2018.8.21 today.

**Comment by codeoriginator** [comment]
Yes, I face the same issue with the latest.

**Comment by maniac0s** [comment]
@lorem--ipsum Could we get a full gruntfile for this solution?

**Comment by arthurlacoste** [comment]
I have the same issue

**Comment by tradingbills** [comment]
Todays date: Sat Mar 23 20:03:07 PDT 2019
Got handed an old Gruntfile.js and had to use the _implementation-fix_ above from lorem--ipsum and also added the 
`npm i -D node-sass grunt-sass`
and it finally worked
