### ISSUE TITLE
Contact, Schema, Version and Response Content-types put on right-hand black section

### ISSUE THREAD

**Issue by mrehder** [sourcey/spectacle#159]
On wind64 under cygwin

The generated pages are incorrectly split in the middle with some items separated on the right-hand side.

The web page has a black section on the right and Contact, Schema, Version and Response Content-types are put onto that black portion.

**Comment by yyamano** [comment]
@mrehder Could you upload screenshots? I can't reproduce the problem.

**Comment by mrehder** [comment]
![spectacle issue](https://user-images.githubusercontent.com/12175335/49732174-b38e6300-fc4b-11e8-9e9c-fbb922172762.png)
picture included
