### ISSUE TITLE
Paths are listed in a different order than specified in swagger file

### ISSUE THREAD

**Issue by arkayz** [sourcey/spectacle#17]
For some odd reason the navigation menu shows the paths in a different (apparently random) order. Am I missing something or why is this happening?

**Comment by kalafut** [comment]
I'm just guessing, but since that paths are part of a dictionary they're unsorted (i.e. unrelated to how they appear in the source file). I know that swagger-ui has settings and custom functions for how you want them to be sorted.

**Comment by arkayz** [comment]
I solved the issue by adding tags to each method. This way they get categorized under Operations and the order is the same as specified in the swagger definition. Without the tags the paths are listed out of order and without Operations.

**Comment by auscaster** [comment]
Reza is correct in that Tags should be used to order methods.

**Comment by auscaster** [comment]
Fixed :)
