### ISSUE TITLE
Add compass/entities installation requirement in README.md

### ISSUE THREAD

**Issue by jean553** [sourcey/spectacle#3]
Hello, 

It seems that "compass" must be installed using gem. If compass is not installed, I get this error message when generating my HTML : 

Task error: { [Error: not found: compass] code: 'ENOENT' }

I also get an error message for the npm module "entities" : 

Task error: { [Error: Cannot find module 'entities'] code: 'MODULE_NOT_FOUND' }

:-)

**Comment by pdhodgkinson** [comment]
Should be fixed by my pull request #5 
Don't think it has anything to do with ruby gems... just a refactor that forgot to remove a reference to a node dependency.

**Comment by b5** [comment]
@jean553 is correct, grunt-contrib-compass tries to call out to a ruby gem (compass), and if it's not installed the grunt task complains. It should also be noted that I had to peg the version of grunt-contrib-compass specifically at 1.0.4 (not higher) to even get to this point. @jean553 did you want to submit a PR, or should I?

Thanks for putting this project together @auscaster!

**Comment by auscaster** [comment]
You're welcome @b5 - a PR would be much welcomed and would no doubt save time for people who aren't familiar or don't work with ruby.
