### ISSUE TITLE
Synchronous CLI calls mix content

### ISSUE THREAD

**Issue by CodeLenny** [sourcey/spectacle#30]
Hi,
I've been starting two Spectacle runs on different files at the same time in a build script, but some of the time (maybe one in four runs) one of the API pages is wrongly embedded in the other.

![spectacle-embedded-obs](https://cloud.githubusercontent.com/assets/9272847/21912075/bd835840-d8f1-11e6-9b6a-1c69442c6d4d.png)

Censored as it's for a closed-source project (my apologies).  Below "Documentation by Spectacle", the other document starts, with the title, schemes, and all routes.

I've paraphrased my Cakefile (CoffeeScript Make alternative).

```coffee
{spawn, exec} = require "child-process-promise"
replace = require "replace-in-file"
chalk = require "chalk"

allSpectacle = (opts) ->
  spectacleDocs opts, "#{__dirname}/src1/api/api.yml", "#{__dirname}/doc/extra/src1/api"
  spectacleDocs opts, "#{__dirname}/src2/api/api.yml", "#{__dirname}/doc/extra/src2/api"

###
Build API docs via [spectacle](https://github.com/sourcey/spectacle)
@param [Object] opts the options passed to `cake`
@param [String] spec a path to the spec-file
@param [String] out a path to the output directory
###
spectacleDocs = (opts, spec, out) ->
  exec "$(npm bin)/spectacle #{spec} -t #{out}"
    .then ->
      replace
        files: "#{out}/index.html"
        replace: /(src|href)="\/\//g
        with: "$1=\"https://"
    .then ->
      replace
        files: "#{out}/index.html"
        replace: /(src|href)="\//g
        with: "$1=\""
    .then ->
      console.log chalk.green "Documented #{chalk.blue spec}"
```

I've changed my build file to run the two Spectacle compiles one after the other which may have fixed it (tested several of times), but it does slow the build down as Spectacle is one of the longer tasks.

**Comment by auscaster** [comment]
This may be due to the cache file not been cleared after running spectacle
each time. Note the `clean:html` task that specifically deletes the
previous HTML cache.

**Comment by CodeLenny** [comment]
@auscaster Could the cache be changed so multiple files could be compiled at once?  I've used [`tmp`](https://www.npmjs.com/package/tmp) before to automatically create a clean directory, which could be used to keep runs separate from each other.

**Comment by auscaster** [comment]
Yes it that could work ... would you be interested in making a PR?

**Comment by CodeLenny** [comment]
@auscaster Sure, I can give it a go.

For my CLI usage, I could just change `program.cacheDir = os.tmpdir() + '/.spectacle';` in `bin/spectacle.js` to use the `tmp` package.

Alternatively, the grunt file (`index.js`) could be altered to generate unique filenames inside `.spectacle`, or call `tmp` internally instead of being passed a temporary directory.

Is one of these an acceptable approach for you?

**Comment by auscaster** [comment]
OK great! Lets just modify program.cacheDir if possible so there's no
regression in other parts of the app that rely on that value.

**Comment by CodeLenny** [comment]
@auscaster I've created a PR.  It looks like the latest release wasn't pushed to GitHub, so you may want to do that before merging.

Thanks!

**Comment by auscaster** [comment]
Thanks again, npm package updated

**Comment by CodeLenny** [comment]
You're welcome, thanks for the quick merge!  Looks like something might have broken in the testing, I didn't see the tests.

**Comment by CodeLenny** [comment]
@auscaster Not just testing, it's failing an assertion.  I'll take a look into it.
