### ISSUE TITLE
Expand types in example requests/responses.

### ISSUE THREAD

**Issue by mikejholly** [sourcey/spectacle#40]
More of a feature request.

It would be awesome if the example response below expanded the `meta` key and showed all fields.

![spectacle](https://cloud.githubusercontent.com/assets/332408/23436526/c3651d96-fdbf-11e6-8fb6-2c2e9ddbfecb.png)

**Comment by auscaster** [comment]
Hi Mike, that would be nice feature!

In the mean time I would suggest adding an `example` to the property since that will be rendered. It may be something like:

```
"properties": {
    "meta": {
        "type": "object",
        "example": { 
            "title": "Gorgonzola",
            "id": 1
        }
    },
    ...
```

**Comment by mikejholly** [comment]
@auscaster Cool, thanks. Would you accept a PR for expanded examples?

**Comment by auscaster** [comment]
Yes a PR would be wonderful :)
