### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by marcottedan** [sourcey/spectacle#50]
Hi!

Would it be possible to hook your Github project's build pipeline into Docker Hub? We did it ourselves but it would be great to have a more "official" support from the project.

https://hub.docker.com/r/alexeiaguiar/spectacle/~/dockerfile/

Thank you

**Comment by marcottedan** [comment]
We did it this way on github: https://github.com/alexeiaguiar/spectacle

**Comment by auscaster** [comment]
Hi Daniel, I haven't had use for this myself yet but would be very happy to
dockerize the repo. If you want to submit a PR with the Dockerfile I will
merge it in, with or without a Docker section in the README which I can
also do myself.

**Comment by auscaster** [comment]
I've added your Docker script to Spectacle so we can call it the official implementation for now. Any updated on your end please push them down the wire. Cheers ;)
