### ISSUE TITLE
Max number of characters doesn't appear when only max specified

### ISSUE THREAD

**Issue by rajivpatel36** [sourcey/spectacle#53]
Looks like there is a typo on [this line](https://github.com/sourcey/spectacle/blob/7a490b7f7e2a07ebec309d66de9446948c59c855/app/views/partials/json-schema/datatype.hbs#L63)

It should say `maxLength` instead of `maxlength`.

Currently the docs produced end up saying something like "(up to chars)" without having the number inserted. I believe this is due to the typo above.

Didn't think this small change was worth a pull request!

**Comment by auscaster** [comment]
Thanks for the PR, the issue has been resolved
