### ISSUE TITLE
Disable file serving

### ISSUE THREAD

**Issue by Korri** [sourcey/spectacle#54]
The documentation specifies that `--development-mode` is `false` by default, but when I run spectacle with no options, it starts a web server and watches my `swagger.yml` file.

Also I did not find any way to disable it.

And thanks for this great package!

**Comment by antimatter96** [comment]
I cant seem to reproduce the issue.
`spectacle "pathTo/swagger.yml"` doesn't seem to start the web server for me

**Comment by Korri** [comment]
You are right, I was using `-d swagger.yml` as a "document" option, when it actually means `--development-mode`, dumb me!
