### ISSUE TITLE
Cannot have more that one json file

### ISSUE THREAD

**Issue by anextro** [sourcey/spectacle#56]
I have tried having more than on configuration file because I have a lot of work to document and it would make sense to separate files for better management.

**Comment by auscaster** [comment]
Multiple failed and remote schema references now work out of the box with spectacle!

You can refer an external document using refs like so: `$ref: 'tag.yml#/Tag/'`

**Comment by zwcampbell** [comment]
@auscaster I'm trying to reference some path information in external .yaml files a la:
`
paths:
  /foo:
    $ref: "myFile.yaml#/paths/~1foo"
`
But it's throwing an error ("Couldn't replace reference"). Is there a different syntax that needs to be used? The aforementioned is working for Swagger UI.
