### ISSUE TITLE
Ordering of operations alphabetically

### ISSUE THREAD

**Issue by automagic** [sourcey/spectacle#74]
The operations are grouped by tag in our swagger.json, but when displayed in spectacle, the operations appear in no particular order; how would we affect the order, for example alphabetically?

**Comment by automagic** [comment]
It looks like the nav.hbs is using #eachSorted helper for sorting tags, but eachSorted is expecting an object with keys, instead of a list of objects (in swagger spec, top level tags key is a list of tag {} objects).   Changing it to #each allows for the swagger to provide the ordering... I will put together a PR.

**Comment by auscaster** [comment]
Hello, a PR to fix this was merged today
