### ISSUE TITLE
Code blocks in operation descriptions are not rendered well by Markdown

### ISSUE THREAD

**Issue by aljp** [sourcey/spectacle#76]
When you include code blocks in the description of an operation it is not rendering the code block well.  
![screenshot 2017-07-13 16 09 30](https://user-images.githubusercontent.com/1378224/28152864-f9c1b134-67e5-11e7-8c2d-b1b669f00346.png)
There is an example where I have modified the code block by wrapping it in `<div class="hljs">`
![screenshot 2017-07-13 16 09 56](https://user-images.githubusercontent.com/1378224/28152886-0f8ac3c0-67e6-11e7-92f1-dea8ced4b490.png)

**Comment by auscaster** [comment]
This one is fixed :)
