### ISSUE TITLE
Objects and arrays

### ISSUE THREAD

**Issue by andrewdonkin** [sourcey/spectacle#77]
Hey, all.

I am trying to document an object containing an array as well as some other fields.  Boiling it down to the bare minimum:

```javascript
{
  "int": "integer",
  "array": [
    {
      "name": "string"
    }
  ]
}
```

I tried two ways:

```yaml
swagger:  2.0

definitions:

  bad_properties_good_example:
    type: object
    properties:
      int:
        type: integer
      array:
        description: An array of dummys
        type: array
        items:
          $ref: '#/definitions/dummy'


  good_properties_bad_example:
    type: object
    properties:
      int:
        type: integer
      array:
        type: array
        $ref: '#/definitions/dummy'
            
  dummy:
    type: object
    properties:
      name:
        type: string
```

The former renders the example perfectly (as pasted in above), but the properties come out as:
```
bad_properties_good_example: object
PROPERTIES
int: integer
array: object[]
An array of dummys
```
...which isn't as useful as it could be.

`good_properties_bad_example` renders the properties as:
```
good_properties_bad_example: object
PROPERTIES
int: integer
array:  Array<dummy>
```
...which is great, especially since "dummy" is a link to its definition, but the example comes out as:
```javascript
{
  "string": "string",
  "array": {
    "name": "string"
  }
}
```

...which is not.

I am new to swagger, so I am hoping that I am just doing it plumb wrong.

Thanks in advance.

**Comment by auscaster** [comment]
Hi there, the answer is to add an `example` member to the `dummy` object. See `test/fixtures/cheese.yml` for a bunch of examples on how to do this. Then `good_properties_bad_example` will render as expected :)

**Comment by andrewdonkin** [comment]
G'day, thanks for getting back.  I wasn't clear enough in the original post I guess, because my problem is  that even with an example, an object containing an array of references such as `good_properties_bad_example`  renders an example like this with no array notation:

```
{
  "int": "integer",
  "array": {
    "name": "Gerald"
  }
}
```
It should look like the one from `bad_properties_good_example`, with array notation:
```
{
  "int": "integer",
  "array": [
    {
      "name": "Gerald"
    }
  ]
}
```

You have been busy so to get these examples I got up to date, added the Gerald example to the dummy, and re-ran green yaml above.

Thanks for the examples in Cheese.yml, but it does not contain arrays of objects, so it does not exhibit the same behaviour I am seeing.

Stumped again.  Hope you can help.

**Comment by guldner** [comment]
Hi 
Having the same problem. 
It can be "solved" it by omitting 'items:' as in "good_properties_bad_example" and adding an example to the type definitions, but I'd prefer to keep the "items": { "$ref: ..." 
\- is it even valid json-schema without?

**Comment by guldner** [comment]
Actually Cheese.yml _does_ contain an array of objects where this issue can be seen:
```yaml
Cheese:
    type: object
    properties:
      tags:
        type: array
        items:
          $ref: 'tag.yml#/Tag/'
```
As can be seen in http://cheesestore.github.io/ the Cheese object does not show a link to the Tag object for the `tags` array property.

**Comment by auscaster** [comment]
Thanks for pointing that out. I'm currently on a hiking trip though and
cant fix it for a couple of weeks. In the mean time a PR wouldn't be
frowned upon if anyone is able :)

**Comment by andrewdonkin** [comment]
@guldner,

> It can be "solved" it by omitting 'items:' as in "good_properties_bad_example" and adding an example to the type definitions, but I'd prefer to keep the "items": { "$ref: ..."

When you say solved, do you mean a link in the properties and array notation in the example?  By what magic did you achieve this, pray tell, because I tried json and yaml, bristling with examples, but no cigar.

Thanks.

**Comment by guldner** [comment]
@andrewdonkin 
Like this. [array_issue.txt](https://github.com/sourcey/spectacle/files/1234301/array_issue.txt)
But again, it's not a real solution. I want `"items:"` in my json-schema :-)

**Comment by andrewdonkin** [comment]
So there is one fix, maybe.  It seems to work:  I diffed two reasonably-sized documents and didn't spot any regression.  I haven't worked with Handlebars before, or even Node, so I won't be crushed if auscaster only uses this as, uh, inspiration.
