### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by beatrizgv** [sourcey/spectacle#78]
Hi,

I would like to know how can I change the initial look&feel of the template after load the swagger file. 

When I modify some parts of the HTML to adjust it to my own information architecture, I see them, but if, after that, I run my swagger file, I lost this HTML configuration and I only can see the typical structure of swagger.

Some ideas?
Thanks!
Beatriz.

**Comment by auscaster** [comment]
Hi there, the way to do this is to copy the `app` folder and customise the templates yourself, then generate spectacle by passing your custom app folder location like so `spectacle -a /path/to/your/app/dir ....`
