### ISSUE TITLE
Build silently without serving

### ISSUE THREAD

**Issue by mousavian** [sourcey/spectacle#79]
I couldn't find any option to build documentation silently without starting the HTTP server; since I need to use spectacle as a part of CI to dynamically generate API doc (and then upload to a storage service). 

If this feature does not exists, I'll be happy to raise a PR for it.

**Comment by theshaunwalker** [comment]
I just run `spectacle spec.json` and that just compiles the files without starting the server. It only starts the server with the `-s` option no?

I may be missing some implicit behaviour as I just then access the files on my system, I've never tried using whatever built-in server spectacle has.

**Comment by auscaster** [comment]
Hi there, just run without -d or -s and you're good to go.

**Comment by mousavian** [comment]
Nice, thank you @theshaunwalker @auscaster
