### ISSUE TITLE
CSS Renders Page sections with large indents

### ISSUE THREAD

**Issue by dongreenmedl** [sourcey/spectacle#86]
I was comparing the documentation that is generated from the recent version (0.9.7) and noticed that the body of each section contains large indents that the example documentation does not have. After inspecting the elements in web debugger, I noticed that the css classes differed dramatically between the example and the recently generated docs. I possibly traced it down to a class `.expanded` that is being applied in the `.row-doc` class but I could not figure out what would be causing the use of the `.expanded` class rather than the normal `.row-doc`. I am unsure if the change in indentation is intentional or is a bug. I much prefer the way the example docs are laid out and would like to figure out how to get that layout back if possible. I used the same `cheese.yml` file to more accurately compare the differences, in case it had something to do with the definitions.

**Current Example Doc**
<img width="1920" alt="screen shot 2017-08-14 at 4 32 06 am" src="https://user-images.githubusercontent.com/25021133/29270049-a8383766-80a9-11e7-9de8-26c2d8f12ecc.png">

**Newly rendered Doc**
<img width="1920" alt="screen shot 2017-08-14 at 4 32 21 am" src="https://user-images.githubusercontent.com/25021133/29270097-ed78979e-80a9-11e7-8cac-2307210568cb.png">

**Comment by auscaster** [comment]
I haven't seen this before! I'm currently away though so can't make a fix.
If you or someone else can push a fix as a PR I would be happy to merge it
in

**Comment by adamlc** [comment]
I'm having this issue too! You can see an example on our [API docs](http://api-v2-docs.jumplead.com/) if it helps!

**Comment by auscaster** [comment]
Hi guys, this one is fixed on 0.9.8
