### ISSUE TITLE
What version of Node do you support?

### ISSUE THREAD

**Issue by synthecypher** [sourcey/spectacle#88]
Could you add a [`engines`](https://docs.npmjs.com/files/package.json#engines) attribute to your `package.json` so we have a rough idea of what version of node this package supports?

Such as the one the tests on Circle CI run against.

**Comment by auscaster** [comment]
Spectacle should run on all node versions - did you have difficulty with a specific version?

**Comment by auscaster** [comment]
Minimum node version supported is 8, which is required by `grunt-sass`
