### ISSUE TITLE
Responses that are defined outside operations are shown as undefined

### ISSUE THREAD

**Issue by heuki** [sourcey/spectacle#91]
It seems to me that spectacle does not support responses when they are not defined inside the paths section but defined in the responses object below the swagger object. In de generated documentation the response is shown as "undefined"

I attached a small example below.
[responses.yaml.txt](https://github.com/sourcey/spectacle/files/1292306/responses.yaml.txt)

**Comment by Depado** [comment]
I'm currently facing the same issue :(

**Comment by schursin** [comment]
@auscaster, please, close this. Fixed in #131.

**Comment by auscaster** [comment]
With pleasure :)
