### ISSUE TITLE
Is there a way to disable the scrolling effect?

### ISSUE THREAD

**Issue by stianlagstad** [sourcey/spectacle#95]
If I start here: http://cheesestore.github.io/ and click the "Customer" link, the site will actually scroll down (through the Cheese and Store operations) and down to Customer. Is there a way to disable that scrolling effect? I'd like to jump straight down to Customer.

**Comment by Enchufadoo** [comment]
This is the first thing I noticed, why have such a long page instead of multiple views, or at least not scrolling.

**Comment by auscaster** [comment]
There is no built in option for this unless you use a custom layout, but you can get the job done easily by removing this line:

```
<script src="javascripts/spectacle.min.js"></script>
```

from `app/views/partials/layout/head.hbs`
